class A
    def f: (Integer) -> Integer | Symbol
    def self.g: (Integer) -> (A % B & C)
    @hello: true
    def initialize: (self) -> ~bot
    
    def thing: (Integer) -> Integer
             | (Symbol) -> Symbol
             | (A) -> C
             | top
end