class A
    def f: (Integer x) -> Integer | Symbol
    def self.g: (Int x) -> (A % B & C)
    @hello: true
    def initialize: (self x) -> ~bot
    
    def thing: (Integer x) -> Integer
             | (Symbol x) -> Symbol
             | (A x) -> C
             | top
end